name: hoisynth_test
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - matplotlib
  - tqdm
  - pip:
    - torch==2.9.1
    - torchvision==0.24.1
    - opencv-python==4.12.0.88
    - ipykernel==7.1.0
    - ipywidgets==8.1.8
    - "git+https://github.com/facebookresearch/detectron2.git"
