_BASE_: ../Base-DA-HOS-ConvNeXt.yaml
MODEL:
  OBJECT_MODULE: False
  MASK_ON: True
  ROI_HEADS:
    NUM_CLASSES: 2
  POINT_HEAD:
    NUM_CLASSES: 2
DATASETS:
  CROSS_DATASET: True
  TRAIN: ("ConvNeXt_S_hoisynth+visor100-T_visor",)
  TRAIN_LABEL: ("ConvNeXt_S_hoisynth+visor100-T_visor",)
  TRAIN_IMAGES_PATH: ("/datasets/HOI-Synth/visor_egohos_synth/images_combined_visor", )
  TRAIN_ANNOTATIONS_PATH: ("/datasets/HOI-Synth/visor_egohos_synth/annotations/combined_visor/train.json", )
  TEST: ("labeled_val",)
  TEST_IMAGES_PATH: ("/datasets/HOI-Synth/visor/images", )
  TEST_ANNOTATIONS_PATH: ("/datasets/HOI-Synth/visor/annotations/val.json", )
  TRAIN_UNLABEL: ("unlabeled_train",)
  TRAIN_UNLABEL_IMAGES_PATH: ("/datasets/HOI-Synth/visor/images", )
  TRAIN_UNLABEL_ANNOTATIONS_PATH: ("/datasets/HOI-Synth/visor/annotations/train_unlabeled.json", )
TEST:
  EVAL_PERIOD: 10000
SOLVER:
  AMP:
    ENABLED: True
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (160000,)
  FACTOR_LIST: (1, 0.1,)
  MAX_ITER: 200000
  CHECKPOINT_PERIOD: 10000
  IMG_PER_BATCH_LABEL: 4
  IMG_PER_BATCH_UNLABEL: 4
  IMS_PER_BATCH: 12
  BASE_LR: 0.0001
  WARMUP_FACTOR: 0.0001
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.05
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "norm"
    CLIP_VALUE: 5.0
SEMISUPNET:
  BURN_UP_STEP: 40000
