_BASE_: Base-DA-HOS-R101-FPN.yaml
MODEL:
  OBJECT_MODULE: False
  MASK_ON: True
  ROI_HEADS:
    NUM_CLASSES: 2
  POINT_HEAD:
    NUM_CLASSES: 2
DATASETS:
  CROSS_DATASET: True
  TRAIN: ("S_hoisynth+egohos10-T_egohos",)
  TRAIN_LABEL: ("S_hoisynth+egohos10-T_egohos",) 
  TRAIN_IMAGES_PATH: ("/datasets/HOI-Synth/visor_egohos_synth/images_combined_egohos", )
  TRAIN_ANNOTATIONS_PATH: ("/datasets/HOI-Synth/visor_egohos_synth/annotations/combined_egohos/train_10.json", )
  TEST: ("labeled_val",)
  TEST_IMAGES_PATH: ("/datasets/HOI-Synth/egohos/images", )
  TEST_ANNOTATIONS_PATH: ("/datasets/HOI-Synth/egohos/annotations/val.json", )
  TRAIN_UNLABEL: ("unlabeled_train",)
  TRAIN_UNLABEL_IMAGES_PATH: ("/datasets/HOI-Synth/egohos/images", )
  TRAIN_UNLABEL_ANNOTATIONS_PATH: ("/datasets/HOI-Synth/egohos/annotations/train.json", )
TEST:
  EVAL_PERIOD: 5000
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (20000, )
  FACTOR_LIST: (1, 0.1, )
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 5000
  IMG_PER_BATCH_LABEL: 4
  IMG_PER_BATCH_UNLABEL: 4
  IMS_PER_BATCH: 12
  BASE_LR: 0.0005
  WARMUP_FACTOR: 0.0001
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
SEMISUPNET:
  BURN_UP_STEP: 10000