BASE: "Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: True
  OBJECT_MODULE: False
  WEIGHTS: "weights/convnext_small.pkl"
  ANCHOR_GENERATOR:
    ANGLES: [[0]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
    IOU_THRESHOLDS: [[0.3, 0.5]]
    SIZES: [[16, 32, 64, 128, 256]]
  BACKBONE:
    NAME: build_convnext_fpn_backbone
    FREEZE_AT: 0
  CONVNEXT:
    DEPTHS: [3, 3, 27, 3]
    DIMS: [96, 192, 384, 768]
    DROP_PATH_RATE: 0.2
    OUT_FEATURES: [0, 1, 2, 3]
  META_ARCHITECTURE: "DAobjTwoStagePseudoLabGeneralizedRCNN"
  FPN:
    IN_FEATURES: [0, 1, 2, 3]
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    PRE_NMS_TOPK_TRAIN: 4000
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TRAIN: 2000
    POST_NMS_TOPK_TEST: 1000
    NMS_THRESH: 0.8
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
  ROI_HEADS:
    NAME: "DAHOSROIHeads"
    LOSS: "CrossEntropy"
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
    BATCH_SIZE_PER_IMAGE: 64
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    TRAIN_ON_PRED_BOXES: True
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
    POOLER_TYPE: ""
    NAME: "PointRendMaskHead"
    FC_DIM: 1024
    NUM_FC: 2
    OUTPUT_SIDE_RESOLUTION: 7
    IN_FEATURES: ["p2"]
    POINT_HEAD_ON: True
  PIXEL_STD: [57.375, 57.120, 58.395]
  POINT_HEAD:
    FC_DIM: 256
    NUM_FC: 3
    IN_FEATURES: ["p2"]
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  RANDOM_FLIP: "none"
  MASK_FORMAT: "bitmask"
SEMISUPNET:
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 20000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 0.5 # 1.0 is suboptimal
  SUP_LOSS_WEIGHT: 1.0
  DIS_TYPE: "p2" #["concate","p2","multi", "res4"]
  DIS_LOSS_WEIGHT: 0.1
VERSION: 2
_BASE_: "Base-RCNN-FPN.yaml"